# -*- coding: utf-8 -*-
"""Simple_code.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SqIZhBLmfGLTeA3wiaZqW9-EMGrGYVGT
"""

# HackBio Histidine Team Stage 0 Script
# Task: Store each team member's details in tuples and print formatted output
#
# Author: Saumi Shah
# Github: https://github.com/saumis22
# LinkedIn: https://www.linkedin.com/in/saumis22
#
# Each tuple holds the following member information:
# (Name, Slack Username, Country, Hobby, Affiliation, Favourite Gene, DNA Sequence)

Samuella = (
    "Samuella Ebeny",       # Name
    "@SamNY",               # Slack Username
    "France",               # Country
    "Reading",              # Hobby
    "Sorbonne University",  # Affiliation
    "SLC9A2",               # Favourite Gene
    "GGAGAGCAGCGCACCGGCATGGGCAGGCGGCCGGCGGCGGAGGGCGGCTGAGGGCTGCTGAG"
)

Archana = (
    "Archana Nadig",
    "@Archana",
    "India",
    "Playing Chess",
    "University of York Uk",
    "Tinman",
    "TCAGTACCAAAATCGAGCTGACAAATTGCAGACACGGTCGAGTGCGCATCGGAACGGCGCTTTACG"
)

Lucia = (
    "Lucia Uchegbu",
    "@Lucia",
    "Nigeria",
    "Social Media Management",
    "Federal University Oye Ekiti",
    "TP53 - Tumor Protein",
    "ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGT"
)

Chimbusonma = (
    "Chimbusonma Amaechina",
    "@Sonma",
    "Nigeria",
    "Reading",
    "Grambling State University, United States",
    "BRCA1",
    "ATGGATTTATCTGCTCTTCGGAAAAGCAAGAGGCTGCTGAGGATCTGAGCTTCTGGAAGTGCTTCTGGAG"
)

Antara = (
    "Antara Ghanta",
    "@Antara",
    "India",
    "Reading",
    "Nottingham Trent University, United Kingdom",
    "HMOX-Heme Oxygenase 1",
    "AACGCCTGCCTCCTCTCGAGCGTCCTCAGCGCAGCCGCCGCCCGCGGAGCCAGCACGAACGAGCCCAGCA"
)

Khanh = (
    "Khanh Gia Duong",
    "@Khanh",
    "Vietnam",
    "Movies",
    "Asian University for Women",
    "BRCA1",
    "ATGGATTTATCTGCTCTTCGGAAAAGCAAGAGGCTGCTGAGGATCTGAGCTTCTGGAAGTGCTTCTGGAG"
)


Saumi = (
    "Saumi Shah",
    "Saumi",
    "USA",
    "Badminton",
    "SJSU",
    "TNF",
    "ATGAGCACTGAAAGCATGATCCG"
)

# Combining all team members into a list for easy iteration
team = [Samuella, Archana, Lucia, Chimbusonma, Antara, Khanh, Saumi]

# Iterate through the list and print the details for each member
for member in team:
    print(f"""
Name: {member[0]}
Slack Username: {member[1]}
Country: {member[2]}
Hobby: {member[3]}
Affiliation: {member[4]}
Favourite Gene: {member[5]}
DNA Sequence of Favourite Gene:
{member[6]}
{'-' * 70}
""")
